### ISSUE TITLE
Extend `MvcMessage` to support `Severity#SUCCESS`

### ISSUE THREAD

**Issue by erdlet** [mvc-toolbox/mvc-toolbox#27]
I think it makes sense to support `SUCCESS` as additional severity, so successful form submissions can be handled more easily.

**Comment by chkal** [comment]
Wouldn't be `SUCCESS` the same as `INFO`?

BTW: Jakarta Faces has `INFO`, `WARN`, `ERROR` and `FATAL`.

**Comment by erdlet** [comment]
I orient myself on the Bootstrap alert types which has `INFO` and `SUCCESS`. For me, `INFO` is something generic, whereas `SUCCESS` implies some successfully performed action.

**Comment by chkal** [comment]
TBH: For me, this is basically the same. But maybe it is just me. :-)

**Comment by erdlet** [comment]
> But maybe it is just me. :-)

Or maybe it's just me who uses a distinct `SUCCESS` type, who knows 🤷🏻 

But anyway, I'm sure we'll survive an additional alert type ;)

**Comment by chkal** [comment]
> But anyway, I'm sure we'll survive an additional alert type ;)

Agreed! :laughing:
