### ISSUE TITLE
JSP Tag for setting the CSRF hidden input field

### ISSUE THREAD

**Issue by erdlet** [mvc-toolbox/mvc-toolbox#28]
In application requiring CSRF protection nearly each form needs an hidden input like this: `<input type="hidden" name="${mvc.csrf.name}" value="${mvc.csrf.token}"/>`. To avoid duplications and mistakes, e. g. by typos, it would be helpful to have
a simple JSP tag. This tag may look like `<t:csrf />` or `<t:csrf context="${mvc}"/>`, where the `context` attribute is type `MvcContext`.

**Comment by chkal** [comment]
Great idea! :+1:
