### ISSUE TITLE
Make array accepting  `Toolbox.t(String, List)` alternative

### ISSUE THREAD

**Issue by erdlet** [mvc-toolbox/mvc-toolbox#29]
When using JSPs, the `Toolbox.t(String, List)` method enforces additional `[ ]` around the value. This is annoying when only a single parameter is passed. So to optimize this, an additional `Toolbox.t(String, String[])` method would be helpful.

**Note:** I think to remember that this design decision is based on Thymeleaf, because afaik it uses `List` when passing collections. Anyway, we should support both.

**Comment by chkal** [comment]
I'm not sure, why we designed it this way. Varargs would best, but IIRC JSP doesn't support this properly?

**Comment by erdlet** [comment]
I had a custom implementation using varargs and it worked perfect. Maybe varargs behavior was fixed in the meanwhile

**Comment by erdlet** [comment]
> I'm not sure, why we designed it this way. 

As I wrote in the description, I think to remember it was because I used an Krazo extension the time I added this code and the extension's template engine used Lists as a default collection parameter type. But it was a long time ago, so I can guarantee for that.
