### ISSUE TITLE
JSP tag to access translations easier

### ISSUE THREAD

**Issue by erdlet** [mvc-toolbox/mvc-toolbox#33]
During the development of a medium complex UI I recognized, that calling `${toolbox.t('someKey')}` is really annoying over the time. Also
the auto-completion for JSP doesn't work that well in my IDE, so this approach is a little bit error prone.

To avoid this, maybe a tag `<t:text key='someKey'/>` can be helpful. This tag accesses the necessary beans and returns the translation.
Also it may have an additional attribute called `value`, which is a kind of fallback or mock.

**Comment by chkal** [comment]
Sure, having such a tag may be valuable in some situations. And I agree that typing something like `${toolbox.t('someKey')}` is not that easy and code completion typically won't work.

Maybe we could even support parameters by something like that:

```xml
<!-- something = Hello {0}! -->
<t:text key="something">
  <t:param value="world"/>
</t:text>

```

**Comment by erdlet** [comment]
> Maybe we could even support parameters by something like that:
>
>
><t:text key="something">
 > <t:param value="world"/>
></t:text>

LGTM, but personally I'd prefer the parameters as a list attribute inside the `<t:text />` tag. Seems easier to use

**Comment by chkal** [comment]
So, basically something like this?

    <t:text key="something" values="${[ 'foo', bar ]}" />

For a literal `foo` and a variable `bar`?

**Comment by erdlet** [comment]
Yes something like this is in my mind. Or `<t:text key="someKey" vars="${['foo', 'bar', baz]}" />`. Anyway, something that makes it easy to access those translations.

**Comment by erdlet** [comment]
List-Handling in JSP tags: https://github.com/javaee/jstl-api/blob/bcbfaa67ef8219cc94764e6ad7eca05a75535f3c/impl/src/main/java/org/apache/taglibs/standard/tag/common/core/ForTokensSupport.java#L67
