### ISSUE TITLE
Let MvcMessage#toString return message?

### ISSUE THREAD

**Issue by erdlet** [mvc-toolbox/mvc-toolbox#35]
I stumbled over this issue a few times now: I'm categorizing my messages inside the controller, so the only thing I need to use
in the UI is the `text` attribute. But often I forget this, so I receive the default `toString` value. To ease the development, we can return the text of the `MvcMessage` in `toString`, so the code get's shorter and the important information is directly usable.

What do you think @chkal?

**Comment by chkal** [comment]
Good idea. I just approved the PR.
